INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (1, UUID(), "Faru (TZH-538) ", 0, "Kukomaa siku 110-120", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (2, UUID(), "Faru (TZH-536) ", 0, "Kukomaa siku 110-120", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (3, UUID(), "Shoka (TZM-523)", 0, "Kukomaa siku 90-110", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (4, UUID(), "Njano Uyole", 0, "Kukomaa siku 90", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (5, UUID(), "Lyamungo 90", 0, "Kukomaa siku 90", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (6, UUID(), "Lyamungo 85", 0, "Kukomaa siku 90", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (7, UUID(), "Jesca", 0, "Kukomaa siku 70", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (8, UUID(), "Mkombozi", 0, "Mihogo", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (9, UUID(), "Mkumba", 0, "Pwani", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (10, UUID(), "Kipusa", 0, "Mihogo", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (11, UUID(), "Chereko", 0, "Mihogo", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (12, UUID(), "Mkuranga-1", 0, "Pwani", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (13, UUID(), "Ontil", 0, "Isiyochagua magugu kwa ajili ya maandalizi ya shamba.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (14, UUID(), "Primagram", 0, "Inatumika kabla ya mazao kuota kwenye mahindi tu.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (15, UUID(), "Bromos", 0, "Inatumika baada ya mazao kuota kwenye mahindi tu.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (16, UUID(), "Sateca", 0, "Inatumika baada ya mazao kuota kwenye maharage tu.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (17, UUID(), "Satecron plus", 0, "Kuzuia na kuzuia viwavi jeshi shambani kwa mazao yote.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (18, UUID(), "Subachlo", 0, "Kuzuia na kuzuia viwavi jeshi shambani kwa mazao yote.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (19, UUID(), "Sosprid", 0, "Kuzuia na kuzuia viwavi jeshi shambani kwa mazao yote.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (20, UUID(), "Nyotaz", 0, "Kwa kuzuia magonjwa kwenye maharage.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (21, UUID(), "Bharaky", 0, "Kwa kuzuia magonjwa kwenye maharage.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (22, UUID(), "Rhoho", 0, "Kwa kuzuia magonjwa kwenye maharage.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (23, UUID(), "Bendera", 0, "Kwa kuzuia magonjwa kwenye maharage.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (24, UUID(), "Subatex", 0, "Kwa kuzuia magonjwa kwenye maharage.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (25, UUID(), "Meru HB  513", 0, "Kukomaa siku 75 -90.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (26, UUID(), "Meru HB 515", 0, "Kukomaa siku 90-110.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (27, UUID(), "Lyamungo 90", 0, "Maharage ya Lyamungo.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (28, UUID(), "Meraxon", 0, "Isiyochagua maguu kwa ajili ya kuandaa shamba.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (29, UUID(), "Agroset", 0, "Isiyochagua maguu kwa ajili ya kuandaa shamba.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (30, UUID(), "Agromine", 0, "Kuua magugu kwenye mahindi tu kabla ya kupanda.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (31, UUID(), "Agro fercron", 0, "Kuzuia na kuuwa wadudu wote na viwavi jeshi shambani.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (32, UUID(), "Protrin", 0, "Kuzuia na kuuwa wadudu wote na viwavi jeshi shambani.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (33, UUID(), "Metakan Super", 0, "Kuzuia na kuuwa wadudu wote na viwavi jeshi shambani.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (34, UUID(), "Agrozeb 80WP(Unga)", 0, "Kuzuia ukungu shambani.", 0, NOW());
INSERT INTO products (id, uuid, name, price, description, created_by, created_at) VALUES (35, UUID(), "Meronil(Maji)", 0, "Kuzuia ukungu shambani.", 0, NOW());
